# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hypermix2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HyperMix2(object):
    def setupUi(self, HyperMix2):
        HyperMix2.setObjectName(_fromUtf8("HyperMix2"))
        HyperMix2.resize(900, 700)
        HyperMix2.setMinimumSize(QtCore.QSize(900, 700))
        font = QtGui.QFont()
        font.setPointSize(11)
        HyperMix2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/H.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HyperMix2.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(HyperMix2)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_16.setMargin(1)
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.diagramPage = QtGui.QWidget()
        self.diagramPage.setObjectName(_fromUtf8("diagramPage"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.diagramPage)
        self.verticalLayout_15.setMargin(11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setMargin(11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pageWidget = QtGui.QToolBox(self.diagramPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageWidget.sizePolicy().hasHeightForWidth())
        self.pageWidget.setSizePolicy(sizePolicy)
        self.pageWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.pageWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        self.pageWidget.setFont(font)
        self.pageWidget.setObjectName(_fromUtf8("pageWidget"))
        self.pageEstimation = QtGui.QWidget()
        self.pageEstimation.setGeometry(QtCore.QRect(0, 0, 250, 458))
        self.pageEstimation.setObjectName(_fromUtf8("pageEstimation"))
        self.pageWidget.addItem(self.pageEstimation, _fromUtf8(""))
        self.pagePreprocessing = QtGui.QWidget()
        self.pagePreprocessing.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.pagePreprocessing.setObjectName(_fromUtf8("pagePreprocessing"))
        self.pageWidget.addItem(self.pagePreprocessing, _fromUtf8(""))
        self.pageExtraction = QtGui.QWidget()
        self.pageExtraction.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.pageExtraction.setObjectName(_fromUtf8("pageExtraction"))
        self.pageWidget.addItem(self.pageExtraction, _fromUtf8(""))
        self.pageAbundance = QtGui.QWidget()
        self.pageAbundance.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.pageAbundance.setObjectName(_fromUtf8("pageAbundance"))
        self.pageWidget.addItem(self.pageAbundance, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.pageWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.workspaceLineEdit = QtGui.QLineEdit(self.diagramPage)
        self.workspaceLineEdit.setReadOnly(True)
        self.workspaceLineEdit.setObjectName(_fromUtf8("workspaceLineEdit"))
        self.verticalLayout.addWidget(self.workspaceLineEdit)
        self.graphicsView = QtGui.QGraphicsView(self.diagramPage)
        self.graphicsView.setMinimumSize(QtCore.QSize(400, 200))
        self.graphicsView.setAcceptDrops(True)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout.addWidget(self.graphicsView)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.diagramPage)
        self.resultsPage = QtGui.QWidget()
        self.resultsPage.setObjectName(_fromUtf8("resultsPage"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.resultsPage)
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.resultsPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabImage = QtGui.QWidget()
        self.tabImage.setObjectName(_fromUtf8("tabImage"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tabImage)
        self.horizontalLayout_12.setMargin(11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setMargin(11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.zPlot = QCustomPlot(self.tabImage)
        self.zPlot.setMinimumSize(QtCore.QSize(300, 175))
        self.zPlot.setMaximumSize(QtCore.QSize(300, 175))
        self.zPlot.setObjectName(_fromUtf8("zPlot"))
        self.verticalLayout_17.addWidget(self.zPlot)
        self.graphicsViewRGB = QtGui.QGraphicsView(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewRGB.sizePolicy().hasHeightForWidth())
        self.graphicsViewRGB.setSizePolicy(sizePolicy)
        self.graphicsViewRGB.setMinimumSize(QtCore.QSize(300, 300))
        self.graphicsViewRGB.setMaximumSize(QtCore.QSize(300, 300))
        self.graphicsViewRGB.setObjectName(_fromUtf8("graphicsViewRGB"))
        self.verticalLayout_17.addWidget(self.graphicsViewRGB)
        self.horizontalLayout_12.addLayout(self.verticalLayout_17)
        self.sliderBands = QtGui.QSlider(self.tabImage)
        self.sliderBands.setMinimumSize(QtCore.QSize(30, 280))
        self.sliderBands.setMaximumSize(QtCore.QSize(30, 280))
        self.sliderBands.setOrientation(QtCore.Qt.Vertical)
        self.sliderBands.setObjectName(_fromUtf8("sliderBands"))
        self.horizontalLayout_12.addWidget(self.sliderBands)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setMargin(11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.comboBoxImages = QtGui.QComboBox(self.tabImage)
        self.comboBoxImages.setObjectName(_fromUtf8("comboBoxImages"))
        self.horizontalLayout_8.addWidget(self.comboBoxImages)
        self.toolButtonLoadImage = QtGui.QToolButton(self.tabImage)
        self.toolButtonLoadImage.setObjectName(_fromUtf8("toolButtonLoadImage"))
        self.horizontalLayout_8.addWidget(self.toolButtonLoadImage)
        self.saveImageButton = QtGui.QPushButton(self.tabImage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveImageButton.sizePolicy().hasHeightForWidth())
        self.saveImageButton.setSizePolicy(sizePolicy)
        self.saveImageButton.setObjectName(_fromUtf8("saveImageButton"))
        self.horizontalLayout_8.addWidget(self.saveImageButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.graphicsViewImages = QtGui.QGraphicsView(self.tabImage)
        self.graphicsViewImages.setMinimumSize(QtCore.QSize(380, 380))
        self.graphicsViewImages.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewImages.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewImages.setObjectName(_fromUtf8("graphicsViewImages"))
        self.verticalLayout_5.addWidget(self.graphicsViewImages)
        self.horizontalLayout_12.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tabImage, _fromUtf8(""))
        self.tabEndmembers = QtGui.QWidget()
        self.tabEndmembers.setObjectName(_fromUtf8("tabEndmembers"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tabEndmembers)
        self.horizontalLayout_11.setMargin(11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBoxEndmembers = QtGui.QComboBox(self.tabEndmembers)
        self.comboBoxEndmembers.setObjectName(_fromUtf8("comboBoxEndmembers"))
        self.horizontalLayout_6.addWidget(self.comboBoxEndmembers)
        self.toolButtonLoadEndmembers = QtGui.QToolButton(self.tabEndmembers)
        self.toolButtonLoadEndmembers.setObjectName(_fromUtf8("toolButtonLoadEndmembers"))
        self.horizontalLayout_6.addWidget(self.toolButtonLoadEndmembers)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.endmemberPlot = QCustomPlot(self.tabEndmembers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endmemberPlot.sizePolicy().hasHeightForWidth())
        self.endmemberPlot.setSizePolicy(sizePolicy)
        self.endmemberPlot.setMinimumSize(QtCore.QSize(300, 300))
        self.endmemberPlot.setObjectName(_fromUtf8("endmemberPlot"))
        self.verticalLayout_3.addWidget(self.endmemberPlot)
        self.comboBoxEnd = QtGui.QComboBox(self.tabEndmembers)
        self.comboBoxEnd.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxEnd.setObjectName(_fromUtf8("comboBoxEnd"))
        self.verticalLayout_3.addWidget(self.comboBoxEnd)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setMargin(11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.comboBoxAbundances = QtGui.QComboBox(self.tabEndmembers)
        self.comboBoxAbundances.setObjectName(_fromUtf8("comboBoxAbundances"))
        self.horizontalLayout_14.addWidget(self.comboBoxAbundances)
        self.toolButtonLoadAbundances = QtGui.QToolButton(self.tabEndmembers)
        self.toolButtonLoadAbundances.setObjectName(_fromUtf8("toolButtonLoadAbundances"))
        self.horizontalLayout_14.addWidget(self.toolButtonLoadAbundances)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.graphicsViewAbundances = QtGui.QGraphicsView(self.tabEndmembers)
        self.graphicsViewAbundances.setMinimumSize(QtCore.QSize(300, 300))
        self.graphicsViewAbundances.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewAbundances.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewAbundances.setObjectName(_fromUtf8("graphicsViewAbundances"))
        self.verticalLayout_4.addWidget(self.graphicsViewAbundances)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.comboBoxAbun = QtGui.QComboBox(self.tabEndmembers)
        self.comboBoxAbun.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxAbun.setObjectName(_fromUtf8("comboBoxAbun"))
        self.horizontalLayout_5.addWidget(self.comboBoxAbun)
        self.lineEditPercentAbun = QtGui.QLineEdit(self.tabEndmembers)
        self.lineEditPercentAbun.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditPercentAbun.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditPercentAbun.setReadOnly(True)
        self.lineEditPercentAbun.setObjectName(_fromUtf8("lineEditPercentAbun"))
        self.horizontalLayout_5.addWidget(self.lineEditPercentAbun)
        self.saveAbundancesButton = QtGui.QPushButton(self.tabEndmembers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAbundancesButton.sizePolicy().hasHeightForWidth())
        self.saveAbundancesButton.setSizePolicy(sizePolicy)
        self.saveAbundancesButton.setObjectName(_fromUtf8("saveAbundancesButton"))
        self.horizontalLayout_5.addWidget(self.saveAbundancesButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tabEndmembers, _fromUtf8(""))
        self.tabRMSE = QtGui.QWidget()
        self.tabRMSE.setObjectName(_fromUtf8("tabRMSE"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tabRMSE)
        self.verticalLayout_19.setMargin(11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setMargin(11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setMargin(11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setMargin(11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_2 = QtGui.QLabel(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_13.addWidget(self.label_2)
        self.comboBoxImageRMSE = QtGui.QComboBox(self.tabRMSE)
        self.comboBoxImageRMSE.setObjectName(_fromUtf8("comboBoxImageRMSE"))
        self.horizontalLayout_13.addWidget(self.comboBoxImageRMSE)
        self.toolButtonLoadImageRMSE = QtGui.QToolButton(self.tabRMSE)
        self.toolButtonLoadImageRMSE.setObjectName(_fromUtf8("toolButtonLoadImageRMSE"))
        self.horizontalLayout_13.addWidget(self.toolButtonLoadImageRMSE)
        self.verticalLayout_18.addLayout(self.horizontalLayout_13)
        self.tabWidget_RMSE = QtGui.QTabWidget(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_RMSE.sizePolicy().hasHeightForWidth())
        self.tabWidget_RMSE.setSizePolicy(sizePolicy)
        self.tabWidget_RMSE.setObjectName(_fromUtf8("tabWidget_RMSE"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setMargin(11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_15.addWidget(self.label_3)
        self.comboBoxAbunRMSE = QtGui.QComboBox(self.tab_2)
        self.comboBoxAbunRMSE.setObjectName(_fromUtf8("comboBoxAbunRMSE"))
        self.horizontalLayout_15.addWidget(self.comboBoxAbunRMSE)
        self.toolButtonLoadAbunRMSE = QtGui.QToolButton(self.tab_2)
        self.toolButtonLoadAbunRMSE.setObjectName(_fromUtf8("toolButtonLoadAbunRMSE"))
        self.horizontalLayout_15.addWidget(self.toolButtonLoadAbunRMSE)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setMargin(11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_16.addWidget(self.label_4)
        self.comboBoxEndRMSE = QtGui.QComboBox(self.tab_2)
        self.comboBoxEndRMSE.setObjectName(_fromUtf8("comboBoxEndRMSE"))
        self.horizontalLayout_16.addWidget(self.comboBoxEndRMSE)
        self.toolButtonLoadEndRMSE = QtGui.QToolButton(self.tab_2)
        self.toolButtonLoadEndRMSE.setObjectName(_fromUtf8("toolButtonLoadEndRMSE"))
        self.horizontalLayout_16.addWidget(self.toolButtonLoadEndRMSE)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.tabWidget_RMSE.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setMargin(11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setMargin(11)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_18.addWidget(self.label_11)
        self.comboBoxImageComparedRMSE = QtGui.QComboBox(self.tab_3)
        self.comboBoxImageComparedRMSE.setObjectName(_fromUtf8("comboBoxImageComparedRMSE"))
        self.horizontalLayout_18.addWidget(self.comboBoxImageComparedRMSE)
        self.toolButtonLoadImageComparedRMSE = QtGui.QToolButton(self.tab_3)
        self.toolButtonLoadImageComparedRMSE.setObjectName(_fromUtf8("toolButtonLoadImageComparedRMSE"))
        self.horizontalLayout_18.addWidget(self.toolButtonLoadImageComparedRMSE)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.tabWidget_RMSE.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_18.addWidget(self.tabWidget_RMSE)
        self.horizontalLayout_25.addLayout(self.verticalLayout_18)
        self.RMSEButton = QtGui.QPushButton(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RMSEButton.sizePolicy().hasHeightForWidth())
        self.RMSEButton.setSizePolicy(sizePolicy)
        self.RMSEButton.setObjectName(_fromUtf8("RMSEButton"))
        self.horizontalLayout_25.addWidget(self.RMSEButton)
        self.verticalLayout_19.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setMargin(11)
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setMargin(11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalSliderBandsRecon = QtGui.QSlider(self.tabRMSE)
        self.horizontalSliderBandsRecon.setEnabled(False)
        self.horizontalSliderBandsRecon.setMinimumSize(QtCore.QSize(340, 0))
        self.horizontalSliderBandsRecon.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBandsRecon.setObjectName(_fromUtf8("horizontalSliderBandsRecon"))
        self.verticalLayout_9.addWidget(self.horizontalSliderBandsRecon)
        self.graphicsViewRecon = QtGui.QGraphicsView(self.tabRMSE)
        self.graphicsViewRecon.setMinimumSize(QtCore.QSize(340, 340))
        self.graphicsViewRecon.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewRecon.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewRecon.setObjectName(_fromUtf8("graphicsViewRecon"))
        self.verticalLayout_9.addWidget(self.graphicsViewRecon)
        self.horizontalLayout_26.addLayout(self.verticalLayout_9)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setMargin(11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.graphicsViewRMSE = QtGui.QGraphicsView(self.tabRMSE)
        self.graphicsViewRMSE.setMinimumSize(QtCore.QSize(340, 340))
        self.graphicsViewRMSE.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewRMSE.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewRMSE.setObjectName(_fromUtf8("graphicsViewRMSE"))
        self.horizontalLayout_7.addWidget(self.graphicsViewRMSE)
        self.graphicsViewScaleBar = QtGui.QGraphicsView(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewScaleBar.sizePolicy().hasHeightForWidth())
        self.graphicsViewScaleBar.setSizePolicy(sizePolicy)
        self.graphicsViewScaleBar.setMinimumSize(QtCore.QSize(50, 340))
        self.graphicsViewScaleBar.setMaximumSize(QtCore.QSize(50, 16777215))
        self.graphicsViewScaleBar.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewScaleBar.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewScaleBar.setObjectName(_fromUtf8("graphicsViewScaleBar"))
        self.horizontalLayout_7.addWidget(self.graphicsViewScaleBar)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_5 = QtGui.QLabel(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_8.addWidget(self.label_5)
        self.lineEditPercentError = QtGui.QLineEdit(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPercentError.sizePolicy().hasHeightForWidth())
        self.lineEditPercentError.setSizePolicy(sizePolicy)
        self.lineEditPercentError.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditPercentError.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditPercentError.setReadOnly(True)
        self.lineEditPercentError.setObjectName(_fromUtf8("lineEditPercentError"))
        self.verticalLayout_8.addWidget(self.lineEditPercentError)
        self.label_10 = QtGui.QLabel(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_8.addWidget(self.label_10)
        self.lineEditNRMSE = QtGui.QLineEdit(self.tabRMSE)
        self.lineEditNRMSE.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditNRMSE.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditNRMSE.setObjectName(_fromUtf8("lineEditNRMSE"))
        self.verticalLayout_8.addWidget(self.lineEditNRMSE)
        self.label_6 = QtGui.QLabel(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.lineEditMeanError = QtGui.QLineEdit(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMeanError.sizePolicy().hasHeightForWidth())
        self.lineEditMeanError.setSizePolicy(sizePolicy)
        self.lineEditMeanError.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditMeanError.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditMeanError.setReadOnly(True)
        self.lineEditMeanError.setObjectName(_fromUtf8("lineEditMeanError"))
        self.verticalLayout_8.addWidget(self.lineEditMeanError)
        self.label_9 = QtGui.QLabel(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_8.addWidget(self.label_9)
        self.lineEditNRMSEMean = QtGui.QLineEdit(self.tabRMSE)
        self.lineEditNRMSEMean.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditNRMSEMean.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditNRMSEMean.setObjectName(_fromUtf8("lineEditNRMSEMean"))
        self.verticalLayout_8.addWidget(self.lineEditNRMSEMean)
        self.label_7 = QtGui.QLabel(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.lineEditMaxError = QtGui.QLineEdit(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMaxError.sizePolicy().hasHeightForWidth())
        self.lineEditMaxError.setSizePolicy(sizePolicy)
        self.lineEditMaxError.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditMaxError.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditMaxError.setReadOnly(True)
        self.lineEditMaxError.setObjectName(_fromUtf8("lineEditMaxError"))
        self.verticalLayout_8.addWidget(self.lineEditMaxError)
        self.label_8 = QtGui.QLabel(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_8.addWidget(self.label_8)
        self.lineEditMinError = QtGui.QLineEdit(self.tabRMSE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMinError.sizePolicy().hasHeightForWidth())
        self.lineEditMinError.setSizePolicy(sizePolicy)
        self.lineEditMinError.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditMinError.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditMinError.setReadOnly(True)
        self.lineEditMinError.setObjectName(_fromUtf8("lineEditMinError"))
        self.verticalLayout_8.addWidget(self.lineEditMinError)
        self.saveRMSEButton = QtGui.QPushButton(self.tabRMSE)
        self.saveRMSEButton.setObjectName(_fromUtf8("saveRMSEButton"))
        self.verticalLayout_8.addWidget(self.saveRMSEButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_9)
        self.verticalLayout_19.addLayout(self.horizontalLayout_26)
        self.tabWidget.addTab(self.tabRMSE, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_14.setMargin(11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setMargin(11)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setMargin(11)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setMargin(11)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_31 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_23.addWidget(self.label_31)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setMargin(11)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.comboBoxRefMatching = QtGui.QComboBox(self.tab)
        self.comboBoxRefMatching.setObjectName(_fromUtf8("comboBoxRefMatching"))
        self.horizontalLayout_21.addWidget(self.comboBoxRefMatching)
        self.toolButtonLoadRefMatching = QtGui.QToolButton(self.tab)
        self.toolButtonLoadRefMatching.setObjectName(_fromUtf8("toolButtonLoadRefMatching"))
        self.horizontalLayout_21.addWidget(self.toolButtonLoadRefMatching)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_21)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.resultsTableRef = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsTableRef.sizePolicy().hasHeightForWidth())
        self.resultsTableRef.setSizePolicy(sizePolicy)
        self.resultsTableRef.setMinimumSize(QtCore.QSize(150, 100))
        self.resultsTableRef.setFrameShape(QtGui.QFrame.NoFrame)
        self.resultsTableRef.setDragDropOverwriteMode(False)
        self.resultsTableRef.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.resultsTableRef.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.resultsTableRef.setGridStyle(QtCore.Qt.CustomDashLine)
        self.resultsTableRef.setRowCount(0)
        self.resultsTableRef.setObjectName(_fromUtf8("resultsTableRef"))
        self.resultsTableRef.setColumnCount(0)
        self.resultsTableRef.horizontalHeader().setVisible(False)
        self.resultsTableRef.verticalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.resultsTableRef)
        self.horizontalLayout_20.addLayout(self.verticalLayout_13)
        self.plotRef = QCustomPlot(self.tab)
        self.plotRef.setMinimumSize(QtCore.QSize(300, 175))
        self.plotRef.setMaximumSize(QtCore.QSize(300, 175))
        self.plotRef.setObjectName(_fromUtf8("plotRef"))
        self.horizontalLayout_20.addWidget(self.plotRef)
        self.verticalLayout_14.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setMargin(11)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setMargin(11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setMargin(11)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_32 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_24.addWidget(self.label_32)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setMargin(11)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.comboBoxSigMatching = QtGui.QComboBox(self.tab)
        self.comboBoxSigMatching.setObjectName(_fromUtf8("comboBoxSigMatching"))
        self.horizontalLayout_22.addWidget(self.comboBoxSigMatching)
        self.toolButtonLoadSigMatching = QtGui.QToolButton(self.tab)
        self.toolButtonLoadSigMatching.setObjectName(_fromUtf8("toolButtonLoadSigMatching"))
        self.horizontalLayout_22.addWidget(self.toolButtonLoadSigMatching)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_22)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.resultsTableSig = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsTableSig.sizePolicy().hasHeightForWidth())
        self.resultsTableSig.setSizePolicy(sizePolicy)
        self.resultsTableSig.setMinimumSize(QtCore.QSize(150, 100))
        self.resultsTableSig.setFrameShape(QtGui.QFrame.NoFrame)
        self.resultsTableSig.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.resultsTableSig.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.resultsTableSig.setGridStyle(QtCore.Qt.CustomDashLine)
        self.resultsTableSig.setRowCount(0)
        self.resultsTableSig.setObjectName(_fromUtf8("resultsTableSig"))
        self.resultsTableSig.setColumnCount(0)
        self.resultsTableSig.horizontalHeader().setVisible(False)
        self.resultsTableSig.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.resultsTableSig)
        self.horizontalLayout_19.addLayout(self.verticalLayout_12)
        self.plotSig = QCustomPlot(self.tab)
        self.plotSig.setMinimumSize(QtCore.QSize(300, 175))
        self.plotSig.setMaximumSize(QtCore.QSize(300, 175))
        self.plotSig.setObjectName(_fromUtf8("plotSig"))
        self.horizontalLayout_19.addWidget(self.plotSig)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditSAD = QtGui.QLineEdit(self.tab)
        self.lineEditSAD.setReadOnly(True)
        self.lineEditSAD.setObjectName(_fromUtf8("lineEditSAD"))
        self.horizontalLayout_3.addWidget(self.lineEditSAD)
        self.comboBoxAuto = QtGui.QComboBox(self.tab)
        self.comboBoxAuto.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxAuto.setObjectName(_fromUtf8("comboBoxAuto"))
        self.horizontalLayout_3.addWidget(self.comboBoxAuto)
        self.comboBoxMatching = QtGui.QComboBox(self.tab)
        self.comboBoxMatching.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxMatching.setObjectName(_fromUtf8("comboBoxMatching"))
        self.horizontalLayout_3.addWidget(self.comboBoxMatching)
        self.helpMatchingButton = QtGui.QPushButton(self.tab)
        self.helpMatchingButton.setEnabled(True)
        self.helpMatchingButton.setMinimumSize(QtCore.QSize(23, 23))
        self.helpMatchingButton.setMaximumSize(QtCore.QSize(23, 23))
        self.helpMatchingButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpMatchingButton.setIcon(icon1)
        self.helpMatchingButton.setObjectName(_fromUtf8("helpMatchingButton"))
        self.horizontalLayout_3.addWidget(self.helpMatchingButton)
        self.matchingButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matchingButton.sizePolicy().hasHeightForWidth())
        self.matchingButton.setSizePolicy(sizePolicy)
        self.matchingButton.setObjectName(_fromUtf8("matchingButton"))
        self.horizontalLayout_3.addWidget(self.matchingButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.resultsPage)
        self.blogPage = QtGui.QWidget()
        self.blogPage.setObjectName(_fromUtf8("blogPage"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.blogPage)
        self.horizontalLayout_10.setMargin(11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.webView = QtWebKit.QWebView(self.blogPage)
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayout_10.addWidget(self.webView)
        self.stackedWidget.addWidget(self.blogPage)
        self.repositoryPage = QtGui.QWidget()
        self.repositoryPage.setObjectName(_fromUtf8("repositoryPage"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.repositoryPage)
        self.horizontalLayout_17.setMargin(11)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.tableWidget = QtGui.QTableWidget(self.repositoryPage)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMinimumSize(QtCore.QSize(565, 0))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setIconSize(QtCore.QSize(30, 30))
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(8)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("ID"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Data Type"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Name"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Lines"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Samples"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Bands"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Interleave"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Thumbnail"))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.horizontalLayout_17.addWidget(self.tableWidget)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.miniView = QtGui.QGraphicsView(self.repositoryPage)
        self.miniView.setMinimumSize(QtCore.QSize(200, 200))
        self.miniView.setMaximumSize(QtCore.QSize(200, 200))
        self.miniView.setObjectName(_fromUtf8("miniView"))
        self.verticalLayout_6.addWidget(self.miniView)
        self.searchLine = QtGui.QLineEdit(self.repositoryPage)
        self.searchLine.setMinimumSize(QtCore.QSize(200, 0))
        self.searchLine.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchLine.setObjectName(_fromUtf8("searchLine"))
        self.verticalLayout_6.addWidget(self.searchLine)
        self.getButton = QtGui.QPushButton(self.repositoryPage)
        self.getButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.getButton.setObjectName(_fromUtf8("getButton"))
        self.verticalLayout_6.addWidget(self.getButton)
        self.horizontalLayout_17.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.repositoryPage)
        self.verticalLayout_16.addWidget(self.stackedWidget)
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(250, 0))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_16.addWidget(self.progressBar)
        HyperMix2.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(HyperMix2)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        HyperMix2.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(HyperMix2)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        HyperMix2.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(HyperMix2)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        HyperMix2.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(HyperMix2)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSet_Workspace = QtGui.QAction(HyperMix2)
        self.actionSet_Workspace.setObjectName(_fromUtf8("actionSet_Workspace"))
        self.actionAbout_HyperMix = QtGui.QAction(HyperMix2)
        self.actionAbout_HyperMix.setObjectName(_fromUtf8("actionAbout_HyperMix"))
        self.actionClear_Console = QtGui.QAction(HyperMix2)
        self.actionClear_Console.setObjectName(_fromUtf8("actionClear_Console"))
        self.actionClear_Info_Panel = QtGui.QAction(HyperMix2)
        self.actionClear_Info_Panel.setObjectName(_fromUtf8("actionClear_Info_Panel"))
        self.actionSnow = QtGui.QAction(HyperMix2)
        self.actionSnow.setObjectName(_fromUtf8("actionSnow"))
        self.actionAntique = QtGui.QAction(HyperMix2)
        self.actionAntique.setObjectName(_fromUtf8("actionAntique"))
        self.actionAzure = QtGui.QAction(HyperMix2)
        self.actionAzure.setObjectName(_fromUtf8("actionAzure"))
        self.actionDark_Slate_Gray = QtGui.QAction(HyperMix2)
        self.actionDark_Slate_Gray.setObjectName(_fromUtf8("actionDark_Slate_Gray"))
        self.actionLight_Salmon = QtGui.QAction(HyperMix2)
        self.actionLight_Salmon.setObjectName(_fromUtf8("actionLight_Salmon"))
        self.actionSmall = QtGui.QAction(HyperMix2)
        self.actionSmall.setObjectName(_fromUtf8("actionSmall"))
        self.actionDefault = QtGui.QAction(HyperMix2)
        self.actionDefault.setObjectName(_fromUtf8("actionDefault"))
        self.actionLarge = QtGui.QAction(HyperMix2)
        self.actionLarge.setObjectName(_fromUtf8("actionLarge"))
        self.actionVery_Large = QtGui.QAction(HyperMix2)
        self.actionVery_Large.setObjectName(_fromUtf8("actionVery_Large"))
        self.actionVery_Small = QtGui.QAction(HyperMix2)
        self.actionVery_Small.setObjectName(_fromUtf8("actionVery_Small"))
        self.actionHelvetica = QtGui.QAction(HyperMix2)
        self.actionHelvetica.setObjectName(_fromUtf8("actionHelvetica"))
        self.actionTimes = QtGui.QAction(HyperMix2)
        self.actionTimes.setObjectName(_fromUtf8("actionTimes"))
        self.actionCourier = QtGui.QAction(HyperMix2)
        self.actionCourier.setObjectName(_fromUtf8("actionCourier"))
        self.actionOldEnglish = QtGui.QAction(HyperMix2)
        self.actionOldEnglish.setObjectName(_fromUtf8("actionOldEnglish"))
        self.action800_x_600 = QtGui.QAction(HyperMix2)
        self.action800_x_600.setObjectName(_fromUtf8("action800_x_600"))
        self.action1024_x_768 = QtGui.QAction(HyperMix2)
        self.action1024_x_768.setObjectName(_fromUtf8("action1024_x_768"))
        self.action1280_x_1024 = QtGui.QAction(HyperMix2)
        self.action1280_x_1024.setObjectName(_fromUtf8("action1280_x_1024"))
        self.action1920_x_1080 = QtGui.QAction(HyperMix2)
        self.action1920_x_1080.setObjectName(_fromUtf8("action1920_x_1080"))
        self.actionDiagram = QtGui.QAction(HyperMix2)
        self.actionDiagram.setObjectName(_fromUtf8("actionDiagram"))
        self.actionResult_Viewer = QtGui.QAction(HyperMix2)
        self.actionResult_Viewer.setObjectName(_fromUtf8("actionResult_Viewer"))
        self.actionResults = QtGui.QAction(HyperMix2)
        self.actionResults.setObjectName(_fromUtf8("actionResults"))
        self.actionOpen_Endmembers_File = QtGui.QAction(HyperMix2)
        self.actionOpen_Endmembers_File.setObjectName(_fromUtf8("actionOpen_Endmembers_File"))
        self.actionBlog = QtGui.QAction(HyperMix2)
        self.actionBlog.setObjectName(_fromUtf8("actionBlog"))
        self.actionRepository = QtGui.QAction(HyperMix2)
        self.actionRepository.setObjectName(_fromUtf8("actionRepository"))
        self.actionConsole = QtGui.QAction(HyperMix2)
        self.actionConsole.setObjectName(_fromUtf8("actionConsole"))
        self.menuFile.addAction(self.actionSet_Workspace)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout_HyperMix)
        self.menuView.addAction(self.actionBlog)
        self.menuView.addAction(self.actionConsole)
        self.menuView.addAction(self.actionDiagram)
        self.menuView.addAction(self.actionResults)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HyperMix2)
        self.stackedWidget.setCurrentIndex(1)
        self.pageWidget.setCurrentIndex(0)
        self.pageWidget.layout().setSpacing(5)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_RMSE.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), HyperMix2.close)
        QtCore.QMetaObject.connectSlotsByName(HyperMix2)

    def retranslateUi(self, HyperMix2):
        HyperMix2.setWindowTitle(_translate("HyperMix2", "HYPERMIX TOOL - HYPERSPECTRAL IMAGES", None))
        self.pageWidget.setItemText(self.pageWidget.indexOf(self.pageEstimation), _translate("HyperMix2", "ENDMEMBER ESTIMATION", None))
        self.pageWidget.setItemText(self.pageWidget.indexOf(self.pagePreprocessing), _translate("HyperMix2", "IMAGE PREPROCESSING", None))
        self.pageWidget.setItemText(self.pageWidget.indexOf(self.pageExtraction), _translate("HyperMix2", "ENDMEMBER EXTRACTION", None))
        self.pageWidget.setItemText(self.pageWidget.indexOf(self.pageAbundance), _translate("HyperMix2", "ABUNDANCE CALCULATION", None))
        self.sliderBands.setStatusTip(_translate("HyperMix2", "Band selector", None))
        self.comboBoxImages.setStatusTip(_translate("HyperMix2", "Images loaded", None))
        self.toolButtonLoadImage.setText(_translate("HyperMix2", "...", None))
        self.saveImageButton.setText(_translate("HyperMix2", "Save as...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImage), _translate("HyperMix2", "Images", None))
        self.comboBoxEndmembers.setStatusTip(_translate("HyperMix2", "Endmember files loaded", None))
        self.toolButtonLoadEndmembers.setText(_translate("HyperMix2", "...", None))
        self.comboBoxAbundances.setStatusTip(_translate("HyperMix2", "Abundance maps loaded", None))
        self.toolButtonLoadAbundances.setText(_translate("HyperMix2", "...", None))
        self.saveAbundancesButton.setText(_translate("HyperMix2", "Save as...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEndmembers), _translate("HyperMix2", "Endmembers", None))
        self.label_2.setText(_translate("HyperMix2", "Image:", None))
        self.toolButtonLoadImageRMSE.setText(_translate("HyperMix2", "...", None))
        self.label_3.setText(_translate("HyperMix2", "Abundances:", None))
        self.toolButtonLoadAbunRMSE.setText(_translate("HyperMix2", "...", None))
        self.label_4.setText(_translate("HyperMix2", "Endmembers:", None))
        self.toolButtonLoadEndRMSE.setText(_translate("HyperMix2", "...", None))
        self.tabWidget_RMSE.setTabText(self.tabWidget_RMSE.indexOf(self.tab_2), _translate("HyperMix2", "From Endmembers and Abundances", None))
        self.label_11.setText(_translate("HyperMix2", "Image to Compare:", None))
        self.toolButtonLoadImageComparedRMSE.setText(_translate("HyperMix2", "...", None))
        self.tabWidget_RMSE.setTabText(self.tabWidget_RMSE.indexOf(self.tab_3), _translate("HyperMix2", "From Image", None))
        self.RMSEButton.setText(_translate("HyperMix2", "RMSE", None))
        self.label_5.setText(_translate("HyperMix2", "Error:", None))
        self.label_10.setText(_translate("HyperMix2", "NRMSE Error:", None))
        self.label_6.setText(_translate("HyperMix2", "Mean Error:", None))
        self.label_9.setText(_translate("HyperMix2", "NRMSE Mean:", None))
        self.label_7.setText(_translate("HyperMix2", "Max Error:", None))
        self.label_8.setText(_translate("HyperMix2", "Min Error:", None))
        self.saveRMSEButton.setText(_translate("HyperMix2", "Save as...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRMSE), _translate("HyperMix2", "RMSE", None))
        self.label_31.setText(_translate("HyperMix2", "Reference spectral signatures:", None))
        self.comboBoxRefMatching.setStatusTip(_translate("HyperMix2", "Endmember files loaded", None))
        self.toolButtonLoadRefMatching.setText(_translate("HyperMix2", "...", None))
        self.label_32.setText(_translate("HyperMix2", "Spectral signatures:", None))
        self.comboBoxSigMatching.setStatusTip(_translate("HyperMix2", "Endmember files loaded", None))
        self.toolButtonLoadSigMatching.setText(_translate("HyperMix2", "...", None))
        self.label.setText(_translate("HyperMix2", "SAD:", None))
        self.matchingButton.setText(_translate("HyperMix2", "MATCH", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("HyperMix2", "SAD", None))
        self.tableWidget.setSortingEnabled(True)
        self.getButton.setText(_translate("HyperMix2", "Download", None))
        self.menuFile.setTitle(_translate("HyperMix2", "File", None))
        self.menuHelp.setTitle(_translate("HyperMix2", "Help", None))
        self.menuView.setTitle(_translate("HyperMix2", "View", None))
        self.actionExit.setText(_translate("HyperMix2", "Exit", None))
        self.actionExit.setShortcut(_translate("HyperMix2", "Alt+Q", None))
        self.actionSet_Workspace.setText(_translate("HyperMix2", "Set Workspace...", None))
        self.actionSet_Workspace.setShortcut(_translate("HyperMix2", "Ctrl+W", None))
        self.actionAbout_HyperMix.setText(_translate("HyperMix2", "About HyperMix...", None))
        self.actionAbout_HyperMix.setShortcut(_translate("HyperMix2", "Ctrl+H", None))
        self.actionClear_Console.setText(_translate("HyperMix2", "Clear Console", None))
        self.actionClear_Info_Panel.setText(_translate("HyperMix2", "Clear Info Panel", None))
        self.actionSnow.setText(_translate("HyperMix2", "Snow", None))
        self.actionAntique.setText(_translate("HyperMix2", "Antique", None))
        self.actionAzure.setText(_translate("HyperMix2", "Azure", None))
        self.actionDark_Slate_Gray.setText(_translate("HyperMix2", "Dark Slate Gray", None))
        self.actionLight_Salmon.setText(_translate("HyperMix2", "Light Salmon", None))
        self.actionSmall.setText(_translate("HyperMix2", "Small", None))
        self.actionDefault.setText(_translate("HyperMix2", "Medium", None))
        self.actionLarge.setText(_translate("HyperMix2", "Large", None))
        self.actionVery_Large.setText(_translate("HyperMix2", "Very Large", None))
        self.actionVery_Small.setText(_translate("HyperMix2", "Very Small", None))
        self.actionHelvetica.setText(_translate("HyperMix2", "Helvetica", None))
        self.actionTimes.setText(_translate("HyperMix2", "Times", None))
        self.actionCourier.setText(_translate("HyperMix2", "Courier", None))
        self.actionOldEnglish.setText(_translate("HyperMix2", "OldEnglish", None))
        self.action800_x_600.setText(_translate("HyperMix2", "800 x 600", None))
        self.action1024_x_768.setText(_translate("HyperMix2", "1024 x 768", None))
        self.action1280_x_1024.setText(_translate("HyperMix2", "1280 x 1024", None))
        self.action1920_x_1080.setText(_translate("HyperMix2", "1920 x 1080", None))
        self.actionDiagram.setText(_translate("HyperMix2", "Diagram", None))
        self.actionDiagram.setShortcut(_translate("HyperMix2", "Ctrl+D", None))
        self.actionResult_Viewer.setText(_translate("HyperMix2", "Result Viewer", None))
        self.actionResults.setText(_translate("HyperMix2", "Results", None))
        self.actionResults.setShortcut(_translate("HyperMix2", "Ctrl+R", None))
        self.actionOpen_Endmembers_File.setText(_translate("HyperMix2", "Open Endmembers File", None))
        self.actionBlog.setText(_translate("HyperMix2", "Blog", None))
        self.actionBlog.setShortcut(_translate("HyperMix2", "Ctrl+B", None))
        self.actionRepository.setText(_translate("HyperMix2", "Repository", None))
        self.actionRepository.setShortcut(_translate("HyperMix2", "Ctrl+E", None))
        self.actionConsole.setText(_translate("HyperMix2", "Console", None))
        self.actionConsole.setShortcut(_translate("HyperMix2", "Ctrl+C", None))

from PyQt4 import QtWebKit
from qcustomplot import QCustomPlot

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    HyperMix2 = QtGui.QMainWindow()
    ui = Ui_HyperMix2()
    ui.setupUi(HyperMix2)
    HyperMix2.show()
    sys.exit(app.exec_())

